[target.aarch64-unknown-linux-musl]
rustflags = [
    "-Ctarget-feature=+lse,+crt-static",
    "-Ctarget-cpu=neoverse-n1",
    "-Zunstable-options",
    "-Cpanic=immediate-abort",
    "-Zpanic_abort_tests",
    "-Zthreads=8",
]
linker = "./linker/cc-aarch64-linux-musl"
ar = "./linker/ar"


[target.x86_64-unknown-linux-musl]
rustflags = [
    "-Ctarget-feature=+crt-static",
    "-Ctarget-cpu=haswell",
    "-Zunstable-options",
    "-Cpanic=immediate-abort",
    "-Zpanic_abort_tests",
    "-Zthreads=8",
]
linker = "./linker/cc-x86_64-linux-musl"
ar = "./linker/ar"

[env]
CC_aarch64_apple_darwin = "/usr/bin/clang"
CC_x86_64_apple_darwin = "/usr/bin/clang"
CXX_aarch64_apple_darwin = "/usr/bin/clang"
CXX_x86_64_apple_darwin = "/usr/bin/clang"

[unstable]
build-std = ["core", "compiler_builtins", "alloc", "std", "panic_abort"]

[target.aarch64-linux-android.env]
ANDROID_ABI = "arm64-v8a"
ANDROID_PLATFORM = "android-24"

CC = "/home/vhxnyu/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang"
CXX = "/home/vhxnyu/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang++"
AR = "/home/vhxnyu/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
CFLAGS = "-march=armv8-a"
CXXFLAGS = "-march=armv8-a"

# cmake 需要这些
CMAKE_C_COMPILER = "/home/vhxnyu/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang"
CMAKE_CXX_COMPILER = "/home/vhxnyu/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang++"
CMAKE_SYSTEM_NAME = "Android"
CMAKE_SYSTEM_VERSION = "24"
CMAKE_ANDROID_ARCH_ABI = "arm64-v8a"
CMAKE_TOOLCHAIN_FILE = "/home/vhxnyu/android-ndk-r27c/build/cmake/android.toolchain.cmake"

BINDGEN_EXTRA_CLANG_ARGS = "--target=aarch64-linux-android24 --sysroot=/home/vhxnyu/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot -I/home/vhxnyu/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/home/vhxnyu/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=24"
